name: ExpandedCooking
main: net.ddns.vcccd.Main
version: 1.2.0
api-version: 1.20
commands:
   setcookingexp:
      description: Sets the players cooking exp
      usage: /<command> <playerName> <cookingExp>
      permission: ExpandedCooking.setEXP
   getcookingexp:
      description: Gets the executors cooking exp
      usage: /<command>
      permission: ExpandedCooking.getEXP
   admindatabase:
      description: Gets Database info
      usage: /<command>
      permission: ExpandedCooking.admin